### ISSUE TITLE
Update title and description in manifest

### ISSUE THREAD

**Issue by meandavejustice** [meandavejustice/pin-tweet-to-ipfs#111]
Looks pretty plain in the chrome://extensions view

<img width="409" alt="CleanShot 2023-01-10 at 16 27 27@2x" src="https://user-images.githubusercontent.com/1844554/211593670-2588347d-0166-43f4-a448-ec3c313d9365.png">

**Comment by tun-ji** [comment]
I'd love to contribute to this! Can this be assigned to me please? (I'd also like to try my best with #64, but I'm not sure what exactly you mean there.

**Comment by meandavejustice** [comment]
@tun-ji This change may cause some issues when uploading to app stores, but feel free to send a pr :)

**Comment by tun-ji** [comment]
Thank you! What kind of issues should I look out for?
